"""
Run once to create recipes.db and seed it with recipe data.
Usage: python init_db.py
"""
import sqlite3, json, os

DB_PATH = os.path.join(os.path.dirname(__file__), "recipes.db")

SCHEMA = """
CREATE TABLE IF NOT EXISTS recipes (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    name                TEXT    NOT NULL,
    category            TEXT    NOT NULL,
    description         TEXT    NOT NULL,
    calories            INTEGER NOT NULL,
    servings            INTEGER NOT NULL,
    prep_time           INTEGER NOT NULL,
    cook_time           INTEGER NOT NULL,
    ingredients         TEXT    NOT NULL,
    steps               TEXT    NOT NULL,
    healthy_description TEXT    NOT NULL,
    healthy_calories    INTEGER NOT NULL,
    healthy_ingredients TEXT    NOT NULL,
    healthy_steps       TEXT    NOT NULL,
    healthy_benefits    TEXT    NOT NULL,
    health_score        INTEGER NOT NULL
);
"""

# ingredient helper
def ing(us, metric, swap=False, swap_from_us=None, swap_from_metric=None, swap_reason=None):
    d = {"us": us, "metric": metric, "swap": swap}
    if swap:
        d["swap_from_us"]     = swap_from_us
        d["swap_from_metric"] = swap_from_metric
        d["swap_reason"]      = swap_reason
    return d

RECIPES = [
    # ── COOKIES ──────────────────────────────────────────────────────────────
    {
        "name": "Chocolate Chip Cookies",
        "category": "Cookies",
        "description": "The classic American cookie — crispy edges, chewy centre, loaded with melty chocolate chips.",
        "calories": 210, "servings": 24, "prep_time": 15, "cook_time": 12,
        "ingredients": [
            ing("2¼ cups all-purpose flour",    "280g all-purpose flour"),
            ing("1 cup (2 sticks) unsalted butter, softened", "225g unsalted butter, softened"),
            ing("¾ cup granulated sugar",        "150g granulated sugar"),
            ing("¾ cup packed brown sugar",      "165g packed brown sugar"),
            ing("2 large eggs",                  "2 large eggs"),
            ing("2 tsp vanilla extract",         "10ml vanilla extract"),
            ing("1 tsp baking soda",             "6g baking soda"),
            ing("1 tsp salt",                    "6g salt"),
            ing("2 cups chocolate chips",        "340g chocolate chips"),
        ],
        "steps": [
            "Preheat oven to 375°F (190°C). Line baking sheets with parchment paper.",
            "Beat butter and both sugars together until light and fluffy, about 3 minutes.",
            "Add eggs one at a time, beating well after each. Mix in vanilla.",
            "Whisk together flour, baking soda, and salt in a separate bowl.",
            "Gradually blend the dry ingredients into the butter mixture.",
            "Stir in chocolate chips.",
            "Drop rounded tablespoons of dough onto prepared sheets, spacing 2 inches apart.",
            "Bake 9–11 minutes until golden brown. Cool on the pan for 2 minutes before transferring.",
        ],
        "healthy_description": "Same satisfying cookie, made with oat flour, coconut oil, and dark chocolate — lower in refined sugar and packed with antioxidants.",
        "healthy_calories": 145,
        "healthy_ingredients": [
            ing("2 cups oat flour",              "200g oat flour",
                swap=True, swap_from_us="2¼ cups all-purpose flour", swap_from_metric="280g all-purpose flour",
                swap_reason="Oat flour adds fibre and has a lower glycemic index"),
            ing("½ cup coconut oil, melted",     "110g coconut oil, melted",
                swap=True, swap_from_us="1 cup butter", swap_from_metric="225g butter",
                swap_reason="Cuts saturated fat significantly; adds medium-chain fatty acids"),
            ing("⅓ cup coconut sugar",           "65g coconut sugar",
                swap=True, swap_from_us="¾ cup granulated sugar", swap_from_metric="150g granulated sugar",
                swap_reason="Lower glycemic index than white sugar"),
            ing("¼ cup maple syrup",             "80ml maple syrup",
                swap=True, swap_from_us="¾ cup brown sugar", swap_from_metric="165g brown sugar",
                swap_reason="Natural sweetener with trace minerals; reduces refined sugar"),
            ing("2 large eggs",                  "2 large eggs"),
            ing("2 tsp vanilla extract",         "10ml vanilla extract"),
            ing("1 tsp baking soda",             "6g baking soda"),
            ing("½ tsp salt",                    "3g salt"),
            ing("1½ cups dark chocolate chips (70%+)", "255g dark chocolate chips (70%+)",
                swap=True, swap_from_us="2 cups chocolate chips", swap_from_metric="340g chocolate chips",
                swap_reason="Higher cacao = more antioxidant flavonoids, less added sugar"),
        ],
        "healthy_steps": [
            "Preheat oven to 350°F (175°C). Line baking sheets with parchment paper.",
            "Whisk together melted coconut oil, coconut sugar, and maple syrup until smooth.",
            "Add eggs and vanilla extract. Whisk until well combined.",
            "Stir in oat flour, baking soda, and salt until a soft dough forms.",
            "Fold in the dark chocolate chips.",
            "Scoop tablespoon-sized balls onto the prepared sheets, spacing 2 inches apart. Flatten slightly.",
            "Bake 10–12 minutes until edges are set. Cookies firm up as they cool — don't overbake.",
        ],
        "healthy_benefits": [
            "~30% fewer calories per cookie than the classic version",
            "Oat flour provides soluble beta-glucan fibre to support healthy cholesterol",
            "Dark chocolate (70%+) delivers antioxidant flavonoids",
            "No refined white sugar — coconut sugar and maple syrup have a lower glycemic impact",
        ],
        "health_score": 7,
    },
    {
        "name": "Oatmeal Raisin Cookies",
        "category": "Cookies",
        "description": "Thick, chewy cookies full of rolled oats, warm cinnamon, and plump raisins. A timeless classic.",
        "calories": 180, "servings": 24, "prep_time": 15, "cook_time": 12,
        "ingredients": [
            ing("1 cup (2 sticks) butter, softened", "225g butter, softened"),
            ing("1 cup granulated sugar",         "200g granulated sugar"),
            ing("1 cup packed brown sugar",       "220g packed brown sugar"),
            ing("2 large eggs",                   "2 large eggs"),
            ing("1 tsp vanilla extract",          "5ml vanilla extract"),
            ing("1½ cups all-purpose flour",      "190g all-purpose flour"),
            ing("1 tsp baking soda",              "6g baking soda"),
            ing("1½ tsp cinnamon",                "4g cinnamon"),
            ing("½ tsp salt",                     "3g salt"),
            ing("3 cups rolled oats",             "270g rolled oats"),
            ing("1 cup raisins",                  "150g raisins"),
        ],
        "steps": [
            "Preheat oven to 350°F (175°C). Line baking sheets with parchment.",
            "Beat butter and both sugars until creamy. Add eggs and vanilla; beat well.",
            "Combine flour, baking soda, cinnamon, and salt in a bowl.",
            "Gradually add flour mixture to butter mixture; mix well.",
            "Stir in oats and raisins.",
            "Drop rounded tablespoons of dough onto baking sheets.",
            "Bake 10–12 minutes until golden. Cool 1 minute before transferring.",
        ],
        "healthy_description": "The same hearty cookie made with whole wheat flour, nut butter instead of butter, and naturally sweetened — no refined sugar.",
        "healthy_calories": 130,
        "healthy_ingredients": [
            ing("½ cup almond butter",            "120g almond butter",
                swap=True, swap_from_us="1 cup butter", swap_from_metric="225g butter",
                swap_reason="Replaces saturated fat with heart-healthy monounsaturated fats and adds protein"),
            ing("¼ cup honey",                    "85g honey",
                swap=True, swap_from_us="1 cup granulated sugar + 1 cup brown sugar", swap_from_metric="420g combined sugars",
                swap_reason="Natural sweetener — dramatically cuts refined sugar content"),
            ing("2 large eggs",                   "2 large eggs"),
            ing("1 tsp vanilla extract",          "5ml vanilla extract"),
            ing("1 cup whole wheat flour",        "120g whole wheat flour",
                swap=True, swap_from_us="1½ cups all-purpose flour", swap_from_metric="190g all-purpose flour",
                swap_reason="Whole wheat retains bran and germ for more fibre and nutrients"),
            ing("1 tsp baking soda",              "6g baking soda"),
            ing("2 tsp cinnamon",                 "5g cinnamon"),
            ing("¼ tsp salt",                     "1.5g salt"),
            ing("3 cups rolled oats",             "270g rolled oats"),
            ing("1 cup raisins",                  "150g raisins"),
        ],
        "healthy_steps": [
            "Preheat oven to 350°F (175°C). Line baking sheets with parchment.",
            "Mix almond butter and honey until smooth. Add eggs and vanilla; stir well.",
            "Add whole wheat flour, baking soda, cinnamon, and salt. Mix until combined.",
            "Fold in oats and raisins. Dough will be thick.",
            "Scoop tablespoon-sized balls onto baking sheets. Flatten slightly.",
            "Bake 10–12 minutes until edges are set. Cool completely before eating — they firm up as they cool.",
        ],
        "healthy_benefits": [
            "No refined sugar — honey provides natural sweetness at a lower glycemic index",
            "Almond butter swaps saturated fat for heart-healthy unsaturated fats",
            "Whole wheat flour adds fibre, B vitamins, and minerals",
            "Oats provide beta-glucan, shown to support healthy cholesterol levels",
        ],
        "health_score": 8,
    },
    {
        "name": "Shortbread Cookies",
        "category": "Cookies",
        "description": "Rich, buttery, melt-in-your-mouth shortbread with just three core ingredients. Simple and indulgent.",
        "calories": 130, "servings": 30, "prep_time": 20, "cook_time": 18,
        "ingredients": [
            ing("1 cup (2 sticks) unsalted butter, softened", "225g unsalted butter, softened"),
            ing("½ cup powdered sugar",           "60g powdered sugar"),
            ing("2 cups all-purpose flour",       "240g all-purpose flour"),
            ing("¼ tsp salt",                     "1.5g salt"),
            ing("1 tsp vanilla extract",          "5ml vanilla extract"),
        ],
        "steps": [
            "Preheat oven to 325°F (165°C). Line baking sheets with parchment.",
            "Beat butter until creamy. Add powdered sugar and beat until fluffy.",
            "Mix in vanilla extract.",
            "Add flour and salt; mix until just combined — do not overwork.",
            "Roll dough to ¼-inch thickness. Cut into shapes.",
            "Place on prepared sheets. Bake 15–18 minutes until just barely golden at edges.",
            "Cool on the pan — they are fragile when warm.",
        ],
        "healthy_description": "A lighter shortbread using almond flour and coconut oil — gluten-free, less sugar, and rich in healthy fats with a delicate nutty flavour.",
        "healthy_calories": 95,
        "healthy_ingredients": [
            ing("2 cups almond flour",            "192g almond flour",
                swap=True, swap_from_us="2 cups all-purpose flour", swap_from_metric="240g all-purpose flour",
                swap_reason="Gluten-free; lower carbs, higher protein and healthy fats"),
            ing("⅓ cup coconut oil, solid",      "75g coconut oil, solid",
                swap=True, swap_from_us="1 cup butter", swap_from_metric="225g butter",
                swap_reason="Cuts calories and saturated fat; adds subtle coconut flavour"),
            ing("3 tbsp maple syrup",             "60ml maple syrup",
                swap=True, swap_from_us="½ cup powdered sugar", swap_from_metric="60g powdered sugar",
                swap_reason="Natural liquid sweetener; a small amount goes a long way"),
            ing("1 tsp vanilla extract",          "5ml vanilla extract"),
            ing("¼ tsp salt",                     "1.5g salt"),
        ],
        "healthy_steps": [
            "Preheat oven to 325°F (165°C). Line a baking sheet with parchment.",
            "Mix almond flour, salt, and solid coconut oil together until crumbly.",
            "Add maple syrup and vanilla; mix until a dough forms.",
            "Roll between two sheets of parchment to ¼-inch thickness.",
            "Cut into shapes and place on prepared sheet. Refrigerate 10 minutes.",
            "Bake 12–15 minutes until lightly golden at edges. Cool completely before handling — they are delicate.",
        ],
        "healthy_benefits": [
            "Gluten-free — suitable for those with gluten intolerance",
            "Almond flour provides vitamin E, magnesium, and fibre",
            "About 25% fewer calories than classic shortbread",
            "No refined sugar — maple syrup adds trace minerals",
        ],
        "health_score": 7,
    },

    # ── CAKES ─────────────────────────────────────────────────────────────────
    {
        "name": "Carrot Cake",
        "category": "Cakes",
        "description": "A moist, warmly spiced cake loaded with freshly grated carrots and topped with classic cream cheese frosting.",
        "calories": 380, "servings": 12, "prep_time": 30, "cook_time": 40,
        "ingredients": [
            ing("2 cups all-purpose flour",       "240g all-purpose flour"),
            ing("2 cups granulated sugar",        "400g granulated sugar"),
            ing("1 cup vegetable oil",            "240ml vegetable oil"),
            ing("4 large eggs",                   "4 large eggs"),
            ing("3 cups grated carrots",          "330g grated carrots"),
            ing("2 tsp baking soda",              "12g baking soda"),
            ing("2 tsp cinnamon",                 "5g cinnamon"),
            ing("½ tsp nutmeg",                   "1.5g nutmeg"),
            ing("½ tsp salt",                     "3g salt"),
            ing("8 oz cream cheese",              "225g cream cheese"),
            ing("¼ cup butter",                   "55g butter"),
            ing("2 cups powdered sugar",          "240g powdered sugar"),
        ],
        "steps": [
            "Preheat oven to 350°F (175°C). Grease two 9-inch round cake pans.",
            "Whisk together flour, baking soda, cinnamon, nutmeg, and salt.",
            "In a large bowl, beat sugar and oil. Add eggs one at a time.",
            "Stir in the dry ingredients until just combined.",
            "Fold in grated carrots.",
            "Divide batter between pans. Bake 35–40 minutes until a toothpick comes out clean.",
            "Cool completely. Beat cream cheese, butter, and powdered sugar for frosting.",
            "Frost the cooled cake and refrigerate until ready to serve.",
        ],
        "healthy_description": "The same comforting carrot cake — whole wheat flour, applesauce replacing half the oil, Greek yogurt frosting, and much less sugar.",
        "healthy_calories": 240,
        "healthy_ingredients": [
            ing("1½ cups whole wheat flour",      "180g whole wheat flour",
                swap=True, swap_from_us="2 cups all-purpose flour", swap_from_metric="240g all-purpose flour",
                swap_reason="More fibre and nutrients from the whole grain"),
            ing("¾ cup coconut sugar",            "150g coconut sugar",
                swap=True, swap_from_us="2 cups granulated sugar", swap_from_metric="400g granulated sugar",
                swap_reason="Lower glycemic index; cuts refined sugar by more than half"),
            ing("½ cup applesauce",               "120g applesauce",
                swap=True, swap_from_us="1 cup vegetable oil", swap_from_metric="240ml vegetable oil",
                swap_reason="Replaces most of the oil — drastically cuts fat and calories"),
            ing("¼ cup coconut oil, melted",      "55g coconut oil, melted"),
            ing("4 large eggs",                   "4 large eggs"),
            ing("3 cups grated carrots",          "330g grated carrots"),
            ing("2 tsp baking soda",              "12g baking soda"),
            ing("2 tsp cinnamon",                 "5g cinnamon"),
            ing("½ tsp nutmeg",                   "1.5g nutmeg"),
            ing("¼ tsp salt",                     "1.5g salt"),
            ing("1½ cups plain Greek yogurt (for frosting)", "360g plain Greek yogurt (for frosting)",
                swap=True, swap_from_us="8 oz cream cheese + 2 cups powdered sugar", swap_from_metric="225g cream cheese + 240g powdered sugar",
                swap_reason="Greek yogurt frosting has 70% fewer calories and adds protein and probiotics"),
            ing("2 tbsp honey (for frosting)",    "40g honey (for frosting)"),
            ing("1 tsp vanilla extract (for frosting)", "5ml vanilla extract (for frosting)"),
        ],
        "healthy_steps": [
            "Preheat oven to 350°F (175°C). Grease two 9-inch round pans.",
            "Whisk whole wheat flour, baking soda, cinnamon, nutmeg, and salt.",
            "In a large bowl, whisk coconut sugar, applesauce, melted coconut oil, and eggs.",
            "Fold in dry ingredients until just combined, then fold in grated carrots.",
            "Divide between pans. Bake 35–38 minutes until a toothpick comes out clean.",
            "Cool completely. Mix Greek yogurt, honey, and vanilla for frosting.",
            "Frost the cooled cake. Refrigerate for at least 1 hour before serving.",
        ],
        "healthy_benefits": [
            "~37% fewer calories per slice than the classic version",
            "Greek yogurt frosting adds protein and probiotics instead of butter and powdered sugar",
            "Applesauce replaces most of the oil — same moistness, far less fat",
            "Coconut sugar lowers the glycemic impact of each slice",
        ],
        "health_score": 8,
    },
    {
        "name": "Lemon Drizzle Cake",
        "category": "Cakes",
        "description": "A zingy, golden loaf cake with a crunchy lemon sugar crust — bright, fragrant, and utterly simple.",
        "calories": 290, "servings": 10, "prep_time": 15, "cook_time": 45,
        "ingredients": [
            ing("1½ cups all-purpose flour",      "190g all-purpose flour"),
            ing("1 cup granulated sugar",         "200g granulated sugar"),
            ing("½ cup (1 stick) butter, softened", "115g butter, softened"),
            ing("2 large eggs",                   "2 large eggs"),
            ing("½ cup whole milk",               "120ml whole milk"),
            ing("Zest of 2 lemons",               "Zest of 2 lemons"),
            ing("1½ tsp baking powder",           "7g baking powder"),
            ing("¼ tsp salt",                     "1.5g salt"),
            ing("Juice of 1 lemon (for drizzle)", "Juice of 1 lemon (for drizzle)"),
            ing("½ cup powdered sugar (for drizzle)", "60g powdered sugar (for drizzle)"),
        ],
        "steps": [
            "Preheat oven to 350°F (175°C). Grease a 9×5 inch loaf pan.",
            "Beat butter and sugar until pale and fluffy.",
            "Add eggs one at a time, beating well after each.",
            "Mix in lemon zest.",
            "Fold in flour, baking powder, and salt alternating with milk.",
            "Pour into pan. Bake 40–45 minutes until a toothpick comes out clean.",
            "Mix lemon juice and powdered sugar. Poke holes in the warm cake with a skewer and pour over the drizzle.",
        ],
        "healthy_description": "Almond flour makes this lemon cake naturally gluten-free; Greek yogurt replaces milk for extra protein, and honey replaces refined sugar.",
        "healthy_calories": 195,
        "healthy_ingredients": [
            ing("2 cups almond flour",            "192g almond flour",
                swap=True, swap_from_us="1½ cups all-purpose flour", swap_from_metric="190g all-purpose flour",
                swap_reason="Gluten-free, lower carbs, adds protein and healthy fats"),
            ing("3 tbsp honey",                   "60g honey",
                swap=True, swap_from_us="1 cup granulated sugar", swap_from_metric="200g granulated sugar",
                swap_reason="Natural sweetener — cuts refined sugar dramatically"),
            ing("¼ cup coconut oil, melted",      "55g coconut oil, melted",
                swap=True, swap_from_us="½ cup butter", swap_from_metric="115g butter",
                swap_reason="Reduces saturated fat; coconut oil adds a subtle richness"),
            ing("2 large eggs",                   "2 large eggs"),
            ing("½ cup plain Greek yogurt",       "120g plain Greek yogurt",
                swap=True, swap_from_us="½ cup whole milk", swap_from_metric="120ml whole milk",
                swap_reason="Adds protein and probiotics; creates a moist, tender crumb"),
            ing("Zest of 2 lemons",               "Zest of 2 lemons"),
            ing("2 tbsp fresh lemon juice",       "30ml fresh lemon juice"),
            ing("1 tsp baking powder",            "5g baking powder"),
            ing("¼ tsp salt",                     "1.5g salt"),
            ing("2 tbsp honey + 2 tbsp lemon juice (for drizzle)", "40g honey + 30ml lemon juice (for drizzle)",
                swap=True, swap_from_us="½ cup powdered sugar + lemon juice", swap_from_metric="60g powdered sugar + lemon juice",
                swap_reason="Honey drizzle instead of pure sugar — same tangy finish with less refined sugar"),
        ],
        "healthy_steps": [
            "Preheat oven to 325°F (165°C). Grease a 9×5 inch loaf pan.",
            "Whisk together melted coconut oil, honey, eggs, Greek yogurt, lemon zest, and lemon juice.",
            "Add almond flour, baking powder, and salt. Stir until a smooth batter forms.",
            "Pour into pan. Bake 40–45 minutes until golden and a toothpick comes out clean.",
            "Warm honey and mix with lemon juice. Poke holes in the warm cake and pour over the honey drizzle.",
            "Cool in pan for 15 minutes before slicing.",
        ],
        "healthy_benefits": [
            "Gluten-free — suitable for those avoiding gluten",
            "~33% fewer calories than the classic version",
            "Greek yogurt adds protein and natural probiotics",
            "No refined sugar — honey provides sweetness with a lower glycemic response",
        ],
        "health_score": 8,
    },
    {
        "name": "Classic Chocolate Cake",
        "category": "Cakes",
        "description": "The ultimate celebration cake — deep chocolate flavour, feather-light layers, and rich buttercream frosting.",
        "calories": 450, "servings": 12, "prep_time": 30, "cook_time": 35,
        "ingredients": [
            ing("2 cups all-purpose flour",       "240g all-purpose flour"),
            ing("2 cups granulated sugar",        "400g granulated sugar"),
            ing("¾ cup cocoa powder",             "75g cocoa powder"),
            ing("2 tsp baking soda",              "12g baking soda"),
            ing("1 tsp baking powder",            "5g baking powder"),
            ing("1 tsp salt",                     "6g salt"),
            ing("2 large eggs",                   "2 large eggs"),
            ing("1 cup buttermilk",               "240ml buttermilk"),
            ing("1 cup strong black coffee",      "240ml strong black coffee"),
            ing("½ cup vegetable oil",            "120ml vegetable oil"),
            ing("2 tsp vanilla extract",          "10ml vanilla extract"),
            ing("1 cup butter (for frosting)",    "225g butter (for frosting)"),
            ing("3 cups powdered sugar (for frosting)", "360g powdered sugar (for frosting)"),
            ing("½ cup cocoa powder (for frosting)", "50g cocoa powder (for frosting)"),
        ],
        "steps": [
            "Preheat oven to 350°F (175°C). Grease two 9-inch round cake pans.",
            "Sift together flour, sugar, cocoa, baking soda, baking powder, and salt.",
            "Add eggs, buttermilk, coffee, oil, and vanilla. Beat on medium for 2 minutes.",
            "Pour into pans. Bake 30–35 minutes until a toothpick comes out clean.",
            "Cool completely before frosting.",
            "Beat butter until fluffy. Sift in powdered sugar and cocoa. Add milk to reach desired consistency.",
            "Frost between layers, then the top and sides.",
        ],
        "healthy_description": "A rich chocolate cake made with black beans for protein and fibre, avocado in the frosting, and less than half the sugar of the original.",
        "healthy_calories": 285,
        "healthy_ingredients": [
            ing("1 can (425g) black beans, drained and rinsed", "1 can (425g) black beans, drained and rinsed",
                swap=True, swap_from_us="2 cups all-purpose flour", swap_from_metric="240g all-purpose flour",
                swap_reason="Replaces flour entirely — adds 6g protein per slice and significant fibre"),
            ing("¾ cup coconut sugar",            "150g coconut sugar",
                swap=True, swap_from_us="2 cups granulated sugar", swap_from_metric="400g granulated sugar",
                swap_reason="Lower glycemic index; reduces total sugar by more than 60%"),
            ing("¾ cup cocoa powder",             "75g cocoa powder"),
            ing("4 large eggs",                   "4 large eggs"),
            ing("¼ cup coconut oil, melted",      "55g coconut oil, melted",
                swap=True, swap_from_us="½ cup vegetable oil", swap_from_metric="120ml vegetable oil",
                swap_reason="Replaces refined vegetable oil with a less processed fat"),
            ing("2 tsp baking powder",            "10g baking powder"),
            ing("1 tsp vanilla extract",          "5ml vanilla extract"),
            ing("¼ tsp salt",                     "1.5g salt"),
            ing("2 ripe avocados (for frosting)", "2 ripe avocados (~300g flesh) (for frosting)",
                swap=True, swap_from_us="1 cup butter (for frosting)", swap_from_metric="225g butter (for frosting)",
                swap_reason="Avocado provides monounsaturated fats and a creamy texture with zero dairy"),
            ing("¼ cup cocoa powder (for frosting)", "25g cocoa powder (for frosting)"),
            ing("3 tbsp maple syrup (for frosting)", "60ml maple syrup (for frosting)",
                swap=True, swap_from_us="3 cups powdered sugar (for frosting)", swap_from_metric="360g powdered sugar (for frosting)",
                swap_reason="Natural sweetener replaces refined powdered sugar in the frosting"),
        ],
        "healthy_steps": [
            "Preheat oven to 350°F (175°C). Grease two 9-inch round cake pans.",
            "Blend black beans in a food processor until completely smooth.",
            "Add eggs, coconut oil, coconut sugar, cocoa, baking powder, vanilla, and salt. Blend until uniform.",
            "Pour into prepared pans. Bake 28–32 minutes until set.",
            "Cool completely. For frosting, blend avocado flesh until smooth.",
            "Add cocoa powder and maple syrup to avocado. Mix until glossy and thick.",
            "Frost the cooled cake. Refrigerate 30 minutes before serving.",
        ],
        "healthy_benefits": [
            "Black beans replace flour — adds protein and fibre while keeping the cake fudgy",
            "Avocado frosting replaces butter — heart-healthy monounsaturated fats, no refined sugar",
            "~37% fewer calories per slice",
            "No refined flour or refined sugar in the entire cake",
        ],
        "health_score": 9,
    },

    # ── BREAD ─────────────────────────────────────────────────────────────────
    {
        "name": "Banana Bread",
        "category": "Bread",
        "description": "A tender, moist loaf packed with ripe banana flavour — the perfect way to use up overripe bananas.",
        "calories": 220, "servings": 10, "prep_time": 15, "cook_time": 60,
        "ingredients": [
            ing("1½ cups all-purpose flour",      "190g all-purpose flour"),
            ing("¾ cup granulated sugar",         "150g granulated sugar"),
            ing("⅓ cup butter, melted",           "75g butter, melted"),
            ing("2 large eggs",                   "2 large eggs"),
            ing("3 ripe bananas, mashed",         "3 ripe bananas, mashed"),
            ing("¼ cup whole milk",               "60ml whole milk"),
            ing("1 tsp baking soda",              "6g baking soda"),
            ing("1 tsp vanilla extract",          "5ml vanilla extract"),
            ing("½ tsp salt",                     "3g salt"),
        ],
        "steps": [
            "Preheat oven to 350°F (175°C). Grease a 9×5 inch loaf pan.",
            "Mash bananas in a large bowl. Stir in melted butter.",
            "Beat in sugar, eggs, and vanilla.",
            "Add milk and mix.",
            "Sprinkle in baking soda and salt. Stir to combine.",
            "Fold in flour until just combined — do not overmix.",
            "Pour into pan. Bake 55–65 minutes until a toothpick comes out clean.",
            "Cool in pan 10 minutes, then transfer to a wire rack.",
        ],
        "healthy_description": "Almond flour makes this banana bread gluten-free and protein-rich. No added sugar — the ripe bananas provide all the sweetness you need.",
        "healthy_calories": 165,
        "healthy_ingredients": [
            ing("2½ cups almond flour",           "240g almond flour",
                swap=True, swap_from_us="1½ cups all-purpose flour", swap_from_metric="190g all-purpose flour",
                swap_reason="Gluten-free, low carb, adds protein and healthy fats; needs no milk to stay moist"),
            ing("3 large ripe bananas, mashed",   "3 large ripe bananas, mashed"),
            ing("3 large eggs",                   "3 large eggs",
                swap=True, swap_from_us="2 large eggs", swap_from_metric="2 large eggs",
                swap_reason="Extra egg adds structure to almond flour batter"),
            ing("2 tbsp coconut oil, melted",     "30ml coconut oil, melted",
                swap=True, swap_from_us="⅓ cup butter, melted", swap_from_metric="75g butter, melted",
                swap_reason="Coconut oil cuts saturated fat; a smaller amount is needed due to almond flour's natural fat content"),
            ing("1 tsp cinnamon",                 "3g cinnamon"),
            ing("1 tsp baking soda",              "6g baking soda"),
            ing("1 tsp vanilla extract",          "5ml vanilla extract"),
            ing("¼ tsp salt",                     "1.5g salt"),
        ],
        "healthy_steps": [
            "Preheat oven to 350°F (175°C). Grease a 9×5 inch loaf pan.",
            "Mash bananas until smooth. Whisk in eggs, melted coconut oil, and vanilla.",
            "Add almond flour, cinnamon, baking soda, and salt. Stir until combined.",
            "Pour batter into prepared pan and smooth the top.",
            "Bake 50–55 minutes until deep golden and a toothpick comes out clean.",
            "Cool in pan 10 minutes before transferring to a wire rack.",
        ],
        "healthy_benefits": [
            "No added sugar — ripe bananas provide natural sweetness",
            "Gluten-free and suitable for low-carb diets",
            "Higher in protein and healthy fats than classic banana bread",
            "Almond flour provides vitamin E and magnesium",
        ],
        "health_score": 9,
    },
    {
        "name": "Classic White Bread",
        "category": "Bread",
        "description": "Soft, pillowy white sandwich bread with a golden crust — perfect for toast or sandwiches.",
        "calories": 140, "servings": 16, "prep_time": 20, "cook_time": 30,
        "ingredients": [
            ing("3 cups all-purpose flour",       "360g all-purpose flour"),
            ing("2¼ tsp active dry yeast",        "7g active dry yeast"),
            ing("1 cup warm water",               "240ml warm water"),
            ing("2 tbsp granulated sugar",        "25g granulated sugar"),
            ing("1½ tsp salt",                    "9g salt"),
            ing("2 tbsp vegetable oil",           "30ml vegetable oil"),
        ],
        "steps": [
            "Dissolve yeast and sugar in warm water. Let stand 5–10 minutes until foamy.",
            "Combine flour and salt in a large bowl. Add yeast mixture and oil.",
            "Knead on a floured surface for 8–10 minutes until smooth and elastic.",
            "Place in a greased bowl, cover, and let rise 1 hour until doubled.",
            "Punch down. Shape into a loaf and place in a greased 9×5 inch pan.",
            "Cover and rise 30 minutes. Preheat oven to 375°F (190°C).",
            "Bake 25–30 minutes until golden and hollow-sounding when tapped.",
        ],
        "healthy_description": "Whole grain bread with added seeds — all the same great texture but with far more fibre, nutrients, and staying power.",
        "healthy_calories": 130,
        "healthy_ingredients": [
            ing("2 cups whole wheat flour",       "240g whole wheat flour",
                swap=True, swap_from_us="3 cups all-purpose flour", swap_from_metric="360g all-purpose flour",
                swap_reason="Retains the bran and germ — more fibre, B vitamins, and minerals"),
            ing("1 cup bread flour",              "120g bread flour"),
            ing("2¼ tsp active dry yeast",        "7g active dry yeast"),
            ing("1 cup warm water",               "240ml warm water"),
            ing("1 tbsp honey",                   "20g honey",
                swap=True, swap_from_us="2 tbsp granulated sugar", swap_from_metric="25g granulated sugar",
                swap_reason="Honey feeds the yeast and adds flavour with a lower glycemic index than white sugar"),
            ing("1½ tsp salt",                    "9g salt"),
            ing("2 tbsp olive oil",               "30ml olive oil",
                swap=True, swap_from_us="2 tbsp vegetable oil", swap_from_metric="30ml vegetable oil",
                swap_reason="Olive oil provides heart-healthy monounsaturated fats"),
            ing("2 tbsp mixed seeds (sunflower, sesame, flax)", "20g mixed seeds",
                swap=True, swap_from_us="(no seeds in classic)", swap_from_metric="(no seeds in classic)",
                swap_reason="Seeds add omega-3s, minerals, and extra fibre"),
        ],
        "healthy_steps": [
            "Dissolve yeast and honey in warm water. Let stand 5–10 minutes until foamy.",
            "Combine whole wheat flour, bread flour, and salt. Add yeast mixture and olive oil.",
            "Knead 10 minutes until smooth. Whole wheat dough is denser — this is normal.",
            "Place in a greased bowl, cover, and let rise 1–1.5 hours until doubled.",
            "Punch down. Flatten slightly and sprinkle seeds over the dough; fold and shape into a loaf.",
            "Place in a greased 9×5 inch pan. Cover and rise 40 minutes. Preheat oven to 375°F (190°C).",
            "Bake 28–32 minutes until deep golden. Cool completely before slicing.",
        ],
        "healthy_benefits": [
            "Whole wheat flour provides 3× the fibre of white flour",
            "Mixed seeds add omega-3 fatty acids, zinc, and magnesium",
            "Olive oil replaces refined vegetable oil with heart-healthy fats",
            "Higher fibre content keeps you fuller for longer",
        ],
        "health_score": 8,
    },

    # ── MUFFINS ───────────────────────────────────────────────────────────────
    {
        "name": "Blueberry Muffins",
        "category": "Muffins",
        "description": "Tall, bakery-style muffins bursting with juicy blueberries and topped with a crunchy sugar crust.",
        "calories": 280, "servings": 12, "prep_time": 15, "cook_time": 22,
        "ingredients": [
            ing("2 cups all-purpose flour",       "240g all-purpose flour"),
            ing("¾ cup granulated sugar",         "150g granulated sugar"),
            ing("½ cup (1 stick) butter, melted", "115g butter, melted"),
            ing("2 large eggs",                   "2 large eggs"),
            ing("1 cup whole milk",               "240ml whole milk"),
            ing("2 tsp baking powder",            "10g baking powder"),
            ing("½ tsp salt",                     "3g salt"),
            ing("1½ cups fresh blueberries",      "225g fresh blueberries"),
            ing("2 tbsp sugar for topping",       "25g sugar for topping"),
        ],
        "steps": [
            "Preheat oven to 400°F (205°C). Line a 12-cup muffin tin.",
            "Whisk together flour, sugar, baking powder, and salt.",
            "In another bowl, whisk melted butter, eggs, and milk.",
            "Fold wet into dry until just combined — lumps are fine.",
            "Gently fold in blueberries.",
            "Fill cups ¾ full. Sprinkle sugar on top.",
            "Bake 18–22 minutes until tops spring back when touched.",
        ],
        "healthy_description": "Whole wheat muffins sweetened with honey, using Greek yogurt instead of butter for protein-packed, fluffy, bakery-worthy results.",
        "healthy_calories": 175,
        "healthy_ingredients": [
            ing("1½ cups whole wheat flour",      "180g whole wheat flour",
                swap=True, swap_from_us="2 cups all-purpose flour", swap_from_metric="240g all-purpose flour",
                swap_reason="More fibre and nutrients than white flour"),
            ing("¼ cup honey",                    "85g honey",
                swap=True, swap_from_us="¾ cup granulated sugar", swap_from_metric="150g granulated sugar",
                swap_reason="Natural sweetener — cuts refined sugar in half"),
            ing("1 cup plain Greek yogurt",       "240g plain Greek yogurt",
                swap=True, swap_from_us="½ cup butter + 1 cup milk", swap_from_metric="115g butter + 240ml milk",
                swap_reason="Replaces both butter and milk — adds protein, reduces fat, keeps muffins moist"),
            ing("2 large eggs",                   "2 large eggs"),
            ing("2 tbsp coconut oil, melted",     "28g coconut oil, melted"),
            ing("2 tsp baking powder",            "10g baking powder"),
            ing("½ tsp baking soda",              "3g baking soda"),
            ing("¼ tsp salt",                     "1.5g salt"),
            ing("1½ cups fresh blueberries",      "225g fresh blueberries"),
        ],
        "healthy_steps": [
            "Preheat oven to 375°F (190°C). Line a 12-cup muffin tin.",
            "Whisk together whole wheat flour, baking powder, baking soda, and salt.",
            "In another bowl, whisk Greek yogurt, honey, eggs, and melted coconut oil.",
            "Fold wet into dry until just combined — do not overmix.",
            "Gently fold in blueberries.",
            "Fill cups ¾ full. Bake 18–22 minutes until golden and a toothpick comes out clean.",
            "Cool in tin 5 minutes before transferring.",
        ],
        "healthy_benefits": [
            "~37% fewer calories than the classic version",
            "Greek yogurt replaces both butter and milk — adds protein, cuts fat",
            "Whole wheat flour provides fibre and B vitamins",
            "No refined sugar — honey sweetens naturally",
        ],
        "health_score": 8,
    },
    {
        "name": "Corn Muffins",
        "category": "Muffins",
        "description": "Golden, slightly sweet cornbread muffins with a tender crumb — the perfect side for soups and chilli.",
        "calories": 210, "servings": 12, "prep_time": 10, "cook_time": 20,
        "ingredients": [
            ing("1 cup cornmeal",                 "150g cornmeal"),
            ing("1 cup all-purpose flour",        "120g all-purpose flour"),
            ing("⅓ cup granulated sugar",         "65g granulated sugar"),
            ing("4 tsp baking powder",            "20g baking powder"),
            ing("½ tsp salt",                     "3g salt"),
            ing("1 cup whole milk",               "240ml whole milk"),
            ing("2 large eggs",                   "2 large eggs"),
            ing("¼ cup butter, melted",           "55g butter, melted"),
        ],
        "steps": [
            "Preheat oven to 400°F (205°C). Line a 12-cup muffin tin.",
            "Combine cornmeal, flour, sugar, baking powder, and salt.",
            "Whisk milk, eggs, and melted butter in a separate bowl.",
            "Fold wet into dry until just combined.",
            "Fill cups ¾ full. Bake 18–20 minutes until golden.",
        ],
        "healthy_description": "Made with almond milk, olive oil, and a touch of honey — same golden cornbread flavour but lighter and dairy-free.",
        "healthy_calories": 155,
        "healthy_ingredients": [
            ing("1 cup cornmeal",                 "150g cornmeal"),
            ing("¾ cup whole wheat flour",        "90g whole wheat flour",
                swap=True, swap_from_us="1 cup all-purpose flour", swap_from_metric="120g all-purpose flour",
                swap_reason="Whole wheat adds fibre and nutrients"),
            ing("2 tbsp honey",                   "40g honey",
                swap=True, swap_from_us="⅓ cup granulated sugar", swap_from_metric="65g granulated sugar",
                swap_reason="Natural sweetener with a lower glycemic index"),
            ing("2 tsp baking powder",            "10g baking powder"),
            ing("¼ tsp salt",                     "1.5g salt"),
            ing("1 cup unsweetened almond milk",  "240ml unsweetened almond milk",
                swap=True, swap_from_us="1 cup whole milk", swap_from_metric="240ml whole milk",
                swap_reason="Dairy-free; lower in saturated fat than whole milk"),
            ing("2 large eggs",                   "2 large eggs"),
            ing("3 tbsp olive oil",               "45ml olive oil",
                swap=True, swap_from_us="¼ cup butter, melted", swap_from_metric="55g butter, melted",
                swap_reason="Heart-healthy monounsaturated fats replace saturated fat from butter"),
        ],
        "healthy_steps": [
            "Preheat oven to 400°F (205°C). Line a 12-cup muffin tin.",
            "Combine cornmeal, whole wheat flour, baking powder, and salt.",
            "Whisk almond milk, eggs, olive oil, and honey in a separate bowl.",
            "Fold wet into dry until just combined.",
            "Fill cups ¾ full. Bake 16–18 minutes until golden.",
        ],
        "healthy_benefits": [
            "Dairy-free — uses almond milk instead of whole milk",
            "Olive oil provides heart-healthy fats instead of saturated butter fat",
            "Whole wheat flour adds fibre and B vitamins",
            "About 25% fewer calories per muffin",
        ],
        "health_score": 7,
    },

    # ── BARS & BROWNIES ───────────────────────────────────────────────────────
    {
        "name": "Chocolate Brownies",
        "category": "Bars & Brownies",
        "description": "Dense, fudgy, crinkle-topped chocolate brownies — intensely chocolatey and irresistibly gooey in the centre.",
        "calories": 245, "servings": 16, "prep_time": 15, "cook_time": 25,
        "ingredients": [
            ing("½ cup (1 stick) butter",         "115g butter"),
            ing("1 cup granulated sugar",         "200g granulated sugar"),
            ing("2 large eggs",                   "2 large eggs"),
            ing("1 tsp vanilla extract",          "5ml vanilla extract"),
            ing("⅓ cup cocoa powder",             "33g cocoa powder"),
            ing("½ cup all-purpose flour",        "60g all-purpose flour"),
            ing("¼ tsp salt",                     "1.5g salt"),
            ing("¼ tsp baking powder",            "1.5g baking powder"),
        ],
        "steps": [
            "Preheat oven to 350°F (175°C). Grease an 8×8 inch pan.",
            "Melt butter in a saucepan. Remove from heat. Stir in sugar, eggs, and vanilla.",
            "Beat in cocoa, flour, salt, and baking powder.",
            "Spread into pan. Bake 25 minutes — toothpick should come out with moist crumbs.",
            "Cool completely before cutting.",
        ],
        "healthy_description": "Black beans replace flour entirely for protein-packed, fudgy brownies. Avocado replaces butter for heart-healthy fats — and you cannot taste the difference.",
        "healthy_calories": 145,
        "healthy_ingredients": [
            ing("1 can (425g) black beans, drained and rinsed", "425g black beans, drained and rinsed",
                swap=True, swap_from_us="½ cup all-purpose flour + ½ cup butter", swap_from_metric="60g flour + 115g butter",
                swap_reason="Replaces flour and most of the fat — adds 4g protein and 4g fibre per brownie"),
            ing("1 ripe avocado",                 "1 ripe avocado (~150g flesh)",
                swap=True, swap_from_us="(see black beans above — replaces butter)", swap_from_metric="(see black beans above)",
                swap_reason="Avocado provides monounsaturated fats for a fudgy texture without dairy"),
            ing("3 large eggs",                   "3 large eggs"),
            ing("3 tbsp honey",                   "60g honey",
                swap=True, swap_from_us="1 cup granulated sugar", swap_from_metric="200g granulated sugar",
                swap_reason="Natural sweetener — cuts refined sugar dramatically"),
            ing("⅓ cup cocoa powder",             "33g cocoa powder"),
            ing("1 tsp vanilla extract",          "5ml vanilla extract"),
            ing("1 tsp baking powder",            "5g baking powder"),
            ing("¼ tsp salt",                     "1.5g salt"),
            ing("½ cup dark chocolate chips (70%+)", "85g dark chocolate chips (70%+)"),
        ],
        "healthy_steps": [
            "Preheat oven to 350°F (175°C). Grease an 8×8 inch pan.",
            "Blend black beans and avocado in a food processor until completely smooth.",
            "Add eggs, honey, cocoa powder, vanilla, baking powder, and salt. Blend until uniform.",
            "Fold in chocolate chips by hand.",
            "Pour into pan and spread evenly. Bake 22–25 minutes until set.",
            "Cool completely before cutting — they firm up significantly as they cool.",
        ],
        "healthy_benefits": [
            "~40% fewer calories than classic brownies",
            "Black beans add protein and fibre — no refined flour needed",
            "No refined sugar — honey provides sweetness naturally",
            "Avocado fat is predominantly monounsaturated — heart-healthy",
        ],
        "health_score": 9,
    },
    {
        "name": "Granola Bars",
        "category": "Bars & Brownies",
        "description": "Chewy, golden bars packed with oats, honey, and dried fruit — a classic lunchbox favourite.",
        "calories": 220, "servings": 16, "prep_time": 10, "cook_time": 25,
        "ingredients": [
            ing("3 cups rolled oats",             "270g rolled oats"),
            ing("⅓ cup butter",                   "75g butter"),
            ing("⅓ cup honey",                    "110g honey"),
            ing("⅓ cup packed brown sugar",       "73g packed brown sugar"),
            ing("½ tsp vanilla extract",          "2.5ml vanilla extract"),
            ing("¼ tsp salt",                     "1.5g salt"),
            ing("1 cup mixed dried fruit",        "150g mixed dried fruit"),
        ],
        "steps": [
            "Preheat oven to 325°F (165°C). Grease an 8×11 inch pan and line with parchment.",
            "Melt butter, honey, brown sugar, vanilla, and salt in a saucepan over medium heat.",
            "Pour over oats and dried fruit. Stir until coated.",
            "Press very firmly into pan.",
            "Bake 22–25 minutes until golden. Cool completely before cutting.",
        ],
        "healthy_description": "Nut butter replaces butter, seeds are added for omega-3s, and brown sugar is cut completely — a genuinely nutritious snack bar.",
        "healthy_calories": 165,
        "healthy_ingredients": [
            ing("3 cups rolled oats",             "270g rolled oats"),
            ing("⅓ cup almond butter",            "80g almond butter",
                swap=True, swap_from_us="⅓ cup butter", swap_from_metric="75g butter",
                swap_reason="Replaces saturated fat with heart-healthy unsaturated fats; adds protein"),
            ing("⅓ cup honey",                    "110g honey"),
            ing("¼ tsp vanilla extract",          "1.25ml vanilla extract"),
            ing("¼ tsp salt",                     "1.5g salt"),
            ing("½ cup mixed dried fruit",        "75g mixed dried fruit"),
            ing("¼ cup pumpkin seeds",            "35g pumpkin seeds",
                swap=True, swap_from_us="(not in classic)", swap_from_metric="(not in classic)",
                swap_reason="Adds zinc, magnesium, and omega-3 fatty acids"),
            ing("2 tbsp chia seeds",              "20g chia seeds",
                swap=True, swap_from_us="(not in classic)", swap_from_metric="(not in classic)",
                swap_reason="Omega-3s, fibre, and calcium in every bite"),
            ing("¼ cup dark chocolate chips (70%+)", "42g dark chocolate chips (70%+)",
                swap=True, swap_from_us="(not in classic)", swap_from_metric="(not in classic)",
                swap_reason="Antioxidant flavonoids and satisfying sweetness with less sugar"),
        ],
        "healthy_steps": [
            "Preheat oven to 325°F (165°C). Line an 8×11 inch pan with parchment.",
            "Warm almond butter and honey in a saucepan until combined. Stir in vanilla and salt.",
            "Pour over oats, seeds, and dried fruit. Stir until evenly coated.",
            "Fold in chocolate chips. Press very firmly into pan — the firmer you press, the better they hold together.",
            "Bake 20–22 minutes until golden on top. Cool completely (at least 2 hours) before cutting.",
        ],
        "healthy_benefits": [
            "Almond butter replaces refined butter — adds protein and healthy fats",
            "Seeds provide omega-3 fatty acids, zinc, and additional fibre",
            "No brown sugar — honey alone provides sweetness",
            "Dark chocolate chips add antioxidants instead of plain sugar",
        ],
        "health_score": 8,
    },
]


def main():
    if os.path.exists(DB_PATH):
        os.remove(DB_PATH)
        print(f"Removed existing {DB_PATH}")

    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.executescript(SCHEMA)

    for r in RECIPES:
        conn.execute(
            """INSERT INTO recipes
               (name, category, description, calories, servings, prep_time, cook_time,
                ingredients, steps, healthy_description, healthy_calories,
                healthy_ingredients, healthy_steps, healthy_benefits, health_score)
               VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
            (
                r["name"], r["category"], r["description"],
                r["calories"], r["servings"], r["prep_time"], r["cook_time"],
                json.dumps(r["ingredients"]),
                json.dumps(r["steps"]),
                r["healthy_description"],
                r["healthy_calories"],
                json.dumps(r["healthy_ingredients"]),
                json.dumps(r["healthy_steps"]),
                json.dumps(r["healthy_benefits"]),
                r["health_score"],
            )
        )

    conn.commit()
    conn.close()
    print(f"✓ Created {DB_PATH} with {len(RECIPES)} recipes.")
    cats = {}
    for r in RECIPES:
        cats[r["category"]] = cats.get(r["category"], 0) + 1
    for cat, count in sorted(cats.items()):
        print(f"  {cat}: {count}")


if __name__ == "__main__":
    main()
